version: "2"
services:
  redis:
    image: "redis:alpine"
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    restart: always
    container_name: resource-watch
    depends_on:
      - redis
