apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}-staging
  name: {name}-staging
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}-staging
    spec:
      containers:
      - name: {name}-staging
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        env:
          - name: SESSION_ENV
            value: "staging"
          - name: SECRET
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SECRET
          - name: USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_USERNAME
          - name: RW_USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW2_USERNAME
          - name: RW_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW2_PASSWORD
          - name: PASSWORD
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_PASSWORD
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
        ports:
          - containerPort: 3000
      restartPolicy: Always
