apiVersion: v1
kind: Service
metadata:
  namespace: prep
  labels:
    name: prep-manager-staging
  name: prep-manager-staging
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: prep-manager-staging
