apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prep-manager
  name: prep-manager
  namespace: prep
spec:
  progressDeadlineSeconds: 2147483647
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: prep-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: prep-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - prep-manager
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: SESSION_ENV
          value: production
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: RW_SECRET
              name: appsecrets
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDIS_URI
              name: dbsecrets
        image: vizzuality/prep-manager
        imagePullPolicy: Always
        name: prep-manager
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
