apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prep
  name: prep-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prep-manager
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
