apiVersion: v1
kind: Service
metadata:
  namespace: prep
  labels:
    name: prep-manager
  name: prep-manager
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: prep-manager
